steps:
- name: bash
  script: |
    #!/usr/bin/env bash
    echo "Hello World"
- name: ubuntu
  script: echo hello
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
  - set -x && \
    gcloud compute ssh php-instance-2 --zone=us-central1-c --project=avian-slice-371209 --command='/bin/sh /home/alt/pull.sh'
#        gcloud compute ssh php-instance-2 --zone=us-central1-c --project=avian-slice-371209  --command='/bin/sh /home/alt/pull.sh'
#options:
#  logging: CLOUD_LOGGING_ONLY
